Write-Host "=== Roadmap.md stale text check (should be empty) ==="
Select-String -Path Roadmap.md -Pattern "RM3,000/mo|RM36,000|repurchase begins|Jun.Jul.*IT staff"
Write-Host "=== Forecast.md stale text check (should be empty) ==="
Select-String -Path Forecast.md -Pattern "RM 3,000|186,691|266,340|Jun 2027.*IT.Transfer|Extracted from"
Write-Host "=== HTML stale text check (should be empty) ==="
Select-String -Path Presentation/QCXIS_Roadmap_Forecast.html -Pattern "Jun.Jul.*IT staff|Infra repurchase begins|RM2,200.*5% p\.a\. &"
Write-Host "=== Roadmap.md NEW text check (should all have matches) ==="
Select-String -Path Roadmap.md -Pattern "RM1,000/mo|Hardware repayment begins|Hardware repayment completes"
Write-Host "=== Forecast.md NEW text check ==="
Select-String -Path Forecast.md -Pattern "217,516|RM 1,000/mo|Infra Repayment|1,576,064"
Write-Host "=== Done ==="
